import { useCallback, useEffect, useRef, useState } from "react";

interface Result {
  url: string;
  title: string;
  excerpt: string;
}

interface PagefindApi {
  search(q: string): Promise<{
    results: {
      data(): Promise<{ url: string; excerpt: string; meta: { title?: string } }>;
    }[];
  }>;
}

let pagefind: PagefindApi | null | undefined;

async function loadPagefind(): Promise<PagefindApi | null> {
  if (pagefind !== undefined) return pagefind;
  try {
    // Generated by `pagefind --site dist` at build time; absent in dev.
    // Kept opaque to Vite so it is resolved in the browser, not bundled.
    const url = "/pagefind/pagefind.js";
    pagefind = (await import(/* @vite-ignore */ url)) as PagefindApi;
  } catch {
    pagefind = null;
  }
  return pagefind;
}

export default function Search() {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<Result[]>([]);
  const [active, setActive] = useState(0);
  const [unavailable, setUnavailable] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const debounce = useRef<ReturnType<typeof setTimeout>>(null);

  // Global shortcuts: "/" or ctrl/cmd+k to open.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const el = e.target as HTMLElement;
      const typing =
        el.tagName === "INPUT" || el.tagName === "TEXTAREA" || el.isContentEditable;
      if ((e.key === "/" && !typing) || ((e.ctrlKey || e.metaKey) && e.key === "k")) {
        e.preventDefault();
        setOpen(true);
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);

  useEffect(() => {
    if (open) inputRef.current?.focus();
    else {
      setQuery("");
      setResults([]);
      setActive(0);
    }
  }, [open]);

  const runSearch = useCallback(async (q: string) => {
    const pf = await loadPagefind();
    if (!pf) {
      setUnavailable(true);
      return;
    }
    if (!q.trim()) {
      setResults([]);
      return;
    }
    const res = await pf.search(q);
    const data = await Promise.all(res.results.slice(0, 10).map((r) => r.data()));
    setResults(
      data.map((d) => ({
        url: d.url,
        title: d.meta.title ?? d.url,
        excerpt: d.excerpt,
      })),
    );
    setActive(0);
  }, []);

  const onInput = (q: string) => {
    setQuery(q);
    if (debounce.current) clearTimeout(debounce.current);
    debounce.current = setTimeout(() => void runSearch(q), 120);
  };

  const onPanelKey = (e: React.KeyboardEvent) => {
    if (e.key === "Escape") setOpen(false);
    else if (e.key === "ArrowDown") {
      e.preventDefault();
      setActive((a) => Math.min(a + 1, results.length - 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setActive((a) => Math.max(a - 1, 0));
    } else if (e.key === "Enter" && results[active]) {
      window.location.href = results[active].url;
    }
  };

  return (
    <>
      <button
        type="button"
        className="search-btn"
        onClick={() => setOpen(true)}
        aria-label="Search posts"
      >
        search <kbd>/</kbd>
      </button>
      {open && (
        <div
          className="search-overlay"
          onMouseDown={(e) => {
            if (e.target === e.currentTarget) setOpen(false);
          }}
        >
          <div
            className="search-panel"
            role="dialog"
            aria-modal="true"
            aria-label="Search"
            onKeyDown={onPanelKey}
          >
            <div className="search-titlebar">
              <span>search ~ pagefind</span>
              <span>esc to close</span>
            </div>
            <div className="search-input-row">
              <span className="caret" aria-hidden="true">
                ❯
              </span>
              <input
                ref={inputRef}
                value={query}
                onChange={(e) => onInput(e.target.value)}
                placeholder="grep the blog…"
                spellCheck={false}
                autoComplete="off"
              />
            </div>
            {unavailable ? (
              <p className="search-empty">
                no index in dev mode — run <code>bun run build</code> to generate it.
              </p>
            ) : query && results.length === 0 ? (
              <p className="search-empty">no matches for “{query}”</p>
            ) : (
              results.length > 0 && (
                <ul className="search-results">
                  {results.map((r, i) => (
                    <li key={r.url} className={i === active ? "active" : ""}>
                      <a href={r.url} onMouseEnter={() => setActive(i)}>
                        <span className="r-title">{r.title}</span>
                        <span
                          className="r-excerpt"
                          // Pagefind excerpts are generated from our own
                          // static content at build time.
                          dangerouslySetInnerHTML={{ __html: r.excerpt }}
                        />
                      </a>
                    </li>
                  ))}
                </ul>
              )
            )}
            <div className="search-hints">
              <span>
                <kbd>↑↓</kbd> navigate
              </span>
              <span>
                <kbd>↵</kbd> open
              </span>
              <span>
                <kbd>esc</kbd> close
              </span>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
